version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ec2-user/python
hooks:
  AfterInstall:
    - location: /home/ec2-user/python/scripts/git_pull.sh
      timeout: 300
      runas: root
