version: 2
jobs:
  deploy:
    docker:
      - image: cdssnc/aws-cli
    steps:
      - run:
          name: "Set AWS region"
          command: aws configure set region us-west-2a
      - run:
          name: "Run AWS CodeDeploy"
          command: aws deploy create-deployment --application-name test_app --deployment-group-name MainDeployGroup --github-location repository="bossjerom2/python",commitId="$CIRCLE_SHA1"
workflows:
  version: 2
  build_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master